<a href="https://colab.research.google.com/github/xl4357/MSSP6070/blob/main/week5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
!git clone https://github.com/xl4357/MSSP6070.git

fatal: destination path 'MSSP6070' already exists and is not an empty directory.

In [69]:
!ls

MSSP6070  sample_data

In [70]:
import pandas as pd

In [71]:
aapl = pd.read_csv("MSSP6070/aapl.csv")
amzn = pd.read_csv("MSSP6070/amzn.csv")
fb = pd.read_csv("MSSP6070/fb.csv")
nflx = pd.read_csv("MSSP6070/nflx.csv")
goog = pd.read_csv("MSSP6070/goog.csv")

In [72]:
aapl["ticker"] = "AAPL"
amzn["ticker"] = "AMZN"
fb["ticker"] = "FB"
nflx["ticker"] = "NFLX"
goog["ticker"] = "GOOG"

In [73]:
aapl.head()

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

In [74]:
stocks = pd.concat(
    [aapl, amzn, fb, nflx, goog],
    ignore_index=True
)

In [75]:
stocks.to_csv("MSSP6070/data/faanf.csv", index=False)

In [76]:
faanf = pd.read_csv("MSSP6070/data/faanf.csv")

In [77]:
faanf["date"] = pd.to_datetime(faanf["date"])
faanf["volume"] = faanf["volume"].astype(int)

In [78]:
faanf = faanf.sort_values(["date", "ticker"])

In [79]:
faanf.nlargest(7, "volume")

          date      open      high       low     close     volume ticker
644 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
555 2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
559 2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
556 2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
182 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
245 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
212 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [80]:
melted = faanf.melt(
    id_vars=["date", "ticker"],
    var_name="variable",
    value_name="value"
)

melted.head()

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02   GOOG     open  1048.3400
4 2018-01-02   NFLX     open   196.1000